# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ModeldbVersioningEntry")

model.instance <- ModeldbVersioningEntry$new()

test_that("repository_id", {
  # tests for the property `repository_id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`repository_id`, "EXPECTED_RESULT")
})

test_that("commit", {
  # tests for the property `commit` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`commit`, "EXPECTED_RESULT")
})

test_that("key_location_map", {
  # tests for the property `key_location_map` (map(VertamodeldbLocation))

  # uncomment below to test the property 
  #expect_equal(model.instance$`key_location_map`, "EXPECTED_RESULT")
})

