# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test VertamodeldbLocation")

model.instance <- VertamodeldbLocation$new()

test_that("location", {
  # tests for the property `location` (array[character])

  # uncomment below to test the property 
  #expect_equal(model.instance$`location`, "EXPECTED_RESULT")
})

