# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ModeldbObservation")

model.instance <- ModeldbObservation$new()

test_that("attribute", {
  # tests for the property `attribute` (CommonKeyValue)

  # uncomment below to test the property 
  #expect_equal(model.instance$`attribute`, "EXPECTED_RESULT")
})

test_that("artifact", {
  # tests for the property `artifact` (CommonArtifact)

  # uncomment below to test the property 
  #expect_equal(model.instance$`artifact`, "EXPECTED_RESULT")
})

test_that("timestamp", {
  # tests for the property `timestamp` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`timestamp`, "EXPECTED_RESULT")
})

test_that("epoch_number", {
  # tests for the property `epoch_number` (object)

  # uncomment below to test the property 
  #expect_equal(model.instance$`epoch_number`, "EXPECTED_RESULT")
})

