# modeldb/DatasetService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ModeldbVersioningEntry
#'
#' @description ModeldbVersioningEntry Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field repository_id  character [optional]
#'
#' @field commit  character [optional]
#'
#' @field key_location_map  named list( \link{VertamodeldbLocation} ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModeldbVersioningEntry <- R6::R6Class(
  'ModeldbVersioningEntry',
  public = list(
    `repository_id` = NULL,
    `commit` = NULL,
    `key_location_map` = NULL,
    initialize = function(
        `repository_id`=NULL, `commit`=NULL, `key_location_map`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`repository_id`)) {
        stopifnot(is.character(`repository_id`), length(`repository_id`) == 1)
        self$`repository_id` <- `repository_id`
      }
      if (!is.null(`commit`)) {
        stopifnot(is.character(`commit`), length(`commit`) == 1)
        self$`commit` <- `commit`
      }
      if (!is.null(`key_location_map`)) {
        stopifnot(is.vector(`key_location_map`), length(`key_location_map`) != 0)
        sapply(`key_location_map`, function(x) stopifnot(R6::is.R6(x)))
        self$`key_location_map` <- `key_location_map`
      }
    },
    toJSON = function() {
      ModeldbVersioningEntryObject <- list()
      if (!is.null(self$`repository_id`)) {
        ModeldbVersioningEntryObject[['repository_id']] <-
          self$`repository_id`
      }
      if (!is.null(self$`commit`)) {
        ModeldbVersioningEntryObject[['commit']] <-
          self$`commit`
      }
      if (!is.null(self$`key_location_map`)) {
        ModeldbVersioningEntryObject[['key_location_map']] <-
          lapply(self$`key_location_map`, function(x) x$toJSON())
      }

      ModeldbVersioningEntryObject
    },
    fromJSON = function(ModeldbVersioningEntryJson) {
      ModeldbVersioningEntryObject <- jsonlite::fromJSON(ModeldbVersioningEntryJson)
      if (!is.null(ModeldbVersioningEntryObject$`repository_id`)) {
        self$`repository_id` <- ModeldbVersioningEntryObject$`repository_id`
      }
      if (!is.null(ModeldbVersioningEntryObject$`commit`)) {
        self$`commit` <- ModeldbVersioningEntryObject$`commit`
      }
      if (!is.null(ModeldbVersioningEntryObject$`key_location_map`)) {
        self$`key_location_map` <- ApiClient$new()$deserializeObj(ModeldbVersioningEntryObject$`key_location_map`, "map(VertamodeldbLocation)", loadNamespace("openapi"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`repository_id`)) {
        sprintf(
        '"repository_id":
          "%s"
                ',
        self$`repository_id`
        )},
        if (!is.null(self$`commit`)) {
        sprintf(
        '"commit":
          "%s"
                ',
        self$`commit`
        )},
        if (!is.null(self$`key_location_map`)) {
        sprintf(
        '"key_location_map":
        %s
',
        jsonlite::toJSON(lapply(self$`key_location_map`, function(x){ x$toJSON() }), auto_unbox = TRUE, digits=NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ModeldbVersioningEntryJson) {
      ModeldbVersioningEntryObject <- jsonlite::fromJSON(ModeldbVersioningEntryJson)
      self$`repository_id` <- ModeldbVersioningEntryObject$`repository_id`
      self$`commit` <- ModeldbVersioningEntryObject$`commit`
      self$`key_location_map` <- ApiClient$new()$deserializeObj(ModeldbVersioningEntryObject$`key_location_map`, "map(VertamodeldbLocation)", loadNamespace("openapi"))
      self
    }
  )
)

