# modeldb/DatasetService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ModeldbFeature
#'
#' @description ModeldbFeature Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field name  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModeldbFeature <- R6::R6Class(
  'ModeldbFeature',
  public = list(
    `name` = NULL,
    initialize = function(
        `name`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
    },
    toJSON = function() {
      ModeldbFeatureObject <- list()
      if (!is.null(self$`name`)) {
        ModeldbFeatureObject[['name']] <-
          self$`name`
      }

      ModeldbFeatureObject
    },
    fromJSON = function(ModeldbFeatureJson) {
      ModeldbFeatureObject <- jsonlite::fromJSON(ModeldbFeatureJson)
      if (!is.null(ModeldbFeatureObject$`name`)) {
        self$`name` <- ModeldbFeatureObject$`name`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ModeldbFeatureJson) {
      ModeldbFeatureObject <- jsonlite::fromJSON(ModeldbFeatureJson)
      self$`name` <- ModeldbFeatureObject$`name`
      self
    }
  )
)

