# modeldb/DatasetService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ModeldbObservation
#'
#' @description ModeldbObservation Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field attribute  \link{CommonKeyValue} [optional]
#'
#' @field artifact  \link{CommonArtifact} [optional]
#'
#' @field timestamp  character [optional]
#'
#' @field epoch_number  object [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModeldbObservation <- R6::R6Class(
  'ModeldbObservation',
  public = list(
    `attribute` = NULL,
    `artifact` = NULL,
    `timestamp` = NULL,
    `epoch_number` = NULL,
    initialize = function(
        `attribute`=NULL, `artifact`=NULL, `timestamp`=NULL, `epoch_number`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`attribute`)) {
        stopifnot(R6::is.R6(`attribute`))
        self$`attribute` <- `attribute`
      }
      if (!is.null(`artifact`)) {
        stopifnot(R6::is.R6(`artifact`))
        self$`artifact` <- `artifact`
      }
      if (!is.null(`timestamp`)) {
        stopifnot(is.character(`timestamp`), length(`timestamp`) == 1)
        self$`timestamp` <- `timestamp`
      }
      if (!is.null(`epoch_number`)) {
        self$`epoch_number` <- `epoch_number`
      }
    },
    toJSON = function() {
      ModeldbObservationObject <- list()
      if (!is.null(self$`attribute`)) {
        ModeldbObservationObject[['attribute']] <-
          self$`attribute`$toJSON()
      }
      if (!is.null(self$`artifact`)) {
        ModeldbObservationObject[['artifact']] <-
          self$`artifact`$toJSON()
      }
      if (!is.null(self$`timestamp`)) {
        ModeldbObservationObject[['timestamp']] <-
          self$`timestamp`
      }
      if (!is.null(self$`epoch_number`)) {
        ModeldbObservationObject[['epoch_number']] <-
          self$`epoch_number`
      }

      ModeldbObservationObject
    },
    fromJSON = function(ModeldbObservationJson) {
      ModeldbObservationObject <- jsonlite::fromJSON(ModeldbObservationJson)
      if (!is.null(ModeldbObservationObject$`attribute`)) {
        attributeObject <- CommonKeyValue$new()
        attributeObject$fromJSON(jsonlite::toJSON(ModeldbObservationObject$attribute, auto_unbox = TRUE, digits = NA))
        self$`attribute` <- attributeObject
      }
      if (!is.null(ModeldbObservationObject$`artifact`)) {
        artifactObject <- CommonArtifact$new()
        artifactObject$fromJSON(jsonlite::toJSON(ModeldbObservationObject$artifact, auto_unbox = TRUE, digits = NA))
        self$`artifact` <- artifactObject
      }
      if (!is.null(ModeldbObservationObject$`timestamp`)) {
        self$`timestamp` <- ModeldbObservationObject$`timestamp`
      }
      if (!is.null(ModeldbObservationObject$`epoch_number`)) {
        self$`epoch_number` <- ModeldbObservationObject$`epoch_number`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`attribute`)) {
        sprintf(
        '"attribute":
        %s
        ',
        jsonlite::toJSON(self$`attribute`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`artifact`)) {
        sprintf(
        '"artifact":
        %s
        ',
        jsonlite::toJSON(self$`artifact`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`timestamp`)) {
        sprintf(
        '"timestamp":
          "%s"
                ',
        self$`timestamp`
        )},
        if (!is.null(self$`epoch_number`)) {
        sprintf(
        '"epoch_number":
          "%s"
                ',
        self$`epoch_number`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ModeldbObservationJson) {
      ModeldbObservationObject <- jsonlite::fromJSON(ModeldbObservationJson)
      self$`attribute` <- CommonKeyValue$new()$fromJSON(jsonlite::toJSON(ModeldbObservationObject$attribute, auto_unbox = TRUE, digits = NA))
      self$`artifact` <- CommonArtifact$new()$fromJSON(jsonlite::toJSON(ModeldbObservationObject$artifact, auto_unbox = TRUE, digits = NA))
      self$`timestamp` <- ModeldbObservationObject$`timestamp`
      self$`epoch_number` <- ModeldbObservationObject$`epoch_number`
      self
    }
  )
)

