# modeldb/DatasetService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title VertamodeldbLocation
#'
#' @description VertamodeldbLocation Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field location  list( character ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
VertamodeldbLocation <- R6::R6Class(
  'VertamodeldbLocation',
  public = list(
    `location` = NULL,
    initialize = function(
        `location`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`location`)) {
        stopifnot(is.vector(`location`), length(`location`) != 0)
        sapply(`location`, function(x) stopifnot(is.character(x)))
        self$`location` <- `location`
      }
    },
    toJSON = function() {
      VertamodeldbLocationObject <- list()
      if (!is.null(self$`location`)) {
        VertamodeldbLocationObject[['location']] <-
          self$`location`
      }

      VertamodeldbLocationObject
    },
    fromJSON = function(VertamodeldbLocationJson) {
      VertamodeldbLocationObject <- jsonlite::fromJSON(VertamodeldbLocationJson)
      if (!is.null(VertamodeldbLocationObject$`location`)) {
        self$`location` <- ApiClient$new()$deserializeObj(VertamodeldbLocationObject$`location`, "array[character]", loadNamespace("openapi"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`location`)) {
        sprintf(
        '"location":
           [%s]
        ',
        paste(unlist(lapply(self$`location`, function(x) paste0('"', x, '"'))), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(VertamodeldbLocationJson) {
      VertamodeldbLocationObject <- jsonlite::fromJSON(VertamodeldbLocationJson)
      self$`location` <- ApiClient$new()$deserializeObj(VertamodeldbLocationObject$`location`, "array[character]", loadNamespace("openapi"))
      self
    }
  )
)

